#! /bin/sh

bspc config border_width        2
bspc config window_gap         8
bspc config top_padding 15
bspc config focus_follows_pointer true

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color "#990069"
bspc config active_border_color "#990069"
bspc config focused_border_color "#FA70E8"
bspc config presel_border_color "#57003C"
bspc config urgent_border_color "#990069"

bspc monitor -d meww meow nyaa myuu uguu mjau chuu

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

export PATH=$PATH:/home/ami/util/bspwm/bspwm/examples/panel
panel &
